# Generated by Django 5.1.7 on 2025-03-20 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TractorBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='tractor_brand_logos/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('engine_power', models.IntegerField(blank=True, help_text='Engine power in HP', null=True)),
                ('engine_type', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('petrol', 'Petrol')], max_length=50, null=True)),
                ('cylinder_count', models.IntegerField(blank=True, null=True)),
                ('fuel_capacity', models.IntegerField(blank=True, help_text='Fuel capacity in liters', null=True)),
                ('mileage', models.FloatField(blank=True, help_text='Mileage in KM per liter', null=True)),
                ('gearbox', models.CharField(blank=True, max_length=50, null=True)),
                ('brake_type', models.CharField(blank=True, max_length=100, null=True)),
                ('steering_type', models.CharField(max_length=100)),
                ('tyre_size', models.CharField(blank=True, max_length=100, null=True)),
                ('hydraulics', models.IntegerField(blank=True, help_text='Hydraulic lift capacity in KG', null=True)),
                ('pto_power', models.IntegerField(blank=True, help_text='PTO power in HP', null=True)),
                ('drive_type', models.CharField(blank=True, choices=[('2WD', '2WD'), ('4WD', '4WD')], max_length=10, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('seller_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ownership_status', models.CharField(blank=True, choices=[('first', 'First Owner'), ('second', 'Second Owner')], max_length=50, null=True)),
                ('insurance_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tractor.tractorbrand')),
            ],
        ),
        migrations.CreateModel(
            name='TractorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tractor_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_tractor.tractor')),
            ],
        ),
    ]
