# Generated by Django 5.1.7 on 2025-03-20 11:36

import app_tractor.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tractor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tractor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tractorbrand',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tractorimage',
            name='created_by',
        ),
        migrations.AddField(
            model_name='tractor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tractors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tractorbrand',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tractor_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tractorimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_tractors', to='app_tractor.tractorbrand'),
        ),
        migrations.AlterField(
            model_name='tractorbrand',
            name='logo',
            field=models.ImageField(upload_to=app_tractor.models.tractor_brand_images_directory_path),
        ),
        migrations.AlterField(
            model_name='tractorimage',
            name='image',
            field=models.ImageField(upload_to=app_tractor.models.tractor_images_directory_path),
        ),
        migrations.AlterField(
            model_name='tractorimage',
            name='tractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractor_images', to='app_tractor.tractor'),
        ),
        migrations.CreateModel(
            name='TractorVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(upload_to=app_tractor.models.tractor_videos_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractor_videos', to='app_tractor.tractor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
