# Generated by Django 5.1.7 on 2025-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tractor', '0002_remove_tractor_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='tractorbrand',
            name='slogan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tractorbrand',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
