# Generated by Django 5.1.7 on 2025-03-21 12:07

import app_tractor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tractor', '0003_tractor_slug_tractorbrand_slogan_tractorbrand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='tractor_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tractorvideo',
            name='video',
            field=models.FileField(upload_to=app_tractor.models.tractor_videos_directory_path),
        ),
    ]
