# Generated by Django 5.1.7 on 2025-03-21 16:55

import app_tractor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tractor', '0004_tractor_tractor_details_alter_tractorvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractorbrand',
            name='brand_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=app_tractor.models.tractor_brand_thumbnails_directory_path),
        ),
    ]
